var scramblesMap = {
    "1": [
        "L' B R' L' R' L R' B' L",
        "B' U' B L R U' R' U' L'",
        "L R B U' B' U' R' U' L'",
        "B' U' R' U' R B L U' L'",
        "L' U' L' U' L U' L' U' L'",
        "L R' B' L B' L' B' R L'",
        "B U' B U' B' U' B U' B",
        "B' U' R' U' L' U' L R B",
        "B' R L' B' L' B L' R' B",
        "B L R U' R' U' L' U' B'"
    ],
    "2": [
        "L' B' R' U R U B U L",
        "R U R' L' B' U B U L",
        "L' B R L' R L R B' L",
        "L' U L' U L U L' U L'",
        "L R' B L B L' B R L'",
        "L U R U B U B' R' L'",
        "L U L' B' R' U R U B",
        "B' R' L' U L U R U B",
        "B U B U B' U B U B",
        "L U R U R' L' B' U B"
    ],
    "3": [
        "R' U' R U R B' R' B",
        "R L R L' R' B' R' B",
        "B' L' B R B' R' L B",
        "R B' R' B' L' B L B",
        "B U B L' B' L U' B'",
        "R B' R' B U B U' B'",
        "B R L' B' L B R' B'",
        "B L U' R U R' L' B'",
        "R' L B L B' L R",
        "R B L' B L B R'"
    ],
    "4": [
        "B U L' B L B' U' B'",
        "B R B' L' B L R' B'",
        "L' B L B R B' R' B'",
        "L' R' L' R L B L B'",
        "L U L' U' L' B L B'",
        "R' U R B' L' B' L B'",
        "B L R U' R' U L' B'",
        "R' U' R B L U L' B'",
        "R' L' B L' B' L' R",
        "R B' L' B' L B' R'"
    ],
    "5": [
        "B' R L' R' B' L U B'",
        "B R' L' B' L B R B'",
        "B R U L U' L' R' B'",
        "B' U R B' L' R' L B'",
        "B' L' R' L B U R",
        "R' B L' B L B R",
        "R U R B' R' B R'",
        "L' B L' B' L U L",
        "L B R B R' B L'",
        "B' R' U' R' U R' B"
    ],
    "6": [
        "L B L' B R B' R' B'",
        "L B R' U' R U L' B'",
        "R' B L B' R B L' B'",
        "L U L U' L' B L' B'",
        "R' B' L' B' L B' R",
        "R B' R B R' U' R'",
        "L' U' L' B L B' L",
        "B R L R' B' U' L'",
        "L B' R B' R' B' L'",
        "B' R U' R U R B"
    ],
    "7": [
        "R' L R' B' R B R L'",
        "R L B L B' L' R' L'",
        "L R U' B' U B R' L'",
        "R' L R U' B' U B L'",
        "L B' R' U R U' B L'",
        "R B L' U' B R' L B",
        "R' L B' L B L R",
        "L' U L U R U R'",
        "R' L R L' R U R'",
        "R U B U B' U R'"
    ],
    "8": [
        "L' U' B' R B' R' B' L",
        "L U' L' B L B' U L'",
        "L U R' L' R L U' L'",
        "L R B' U' B U R' L'",
        "L B' U R' U' R B L'",
        "L' B' R U B' L R' B'",
        "L U R' U' L' U R",
        "R U' R' L R' L' R",
        "R' L' B' L' B L' R",
        "R U' B U' B' U' R'"
    ],
    "9": [
        "B U' B L B' L' U B'",
        "B U L B L' B' U' B'",
        "L' R' L R L B L' B'",
        "R' U R' U R U R",
        "B' U B L' R' L R",
        "L R B R B' L' R",
        "R U' R' U R U' R'",
        "L' B' R' U R B L",
        "L U B' U B U' L'",
        "L B R' B R B L'"
    ],
    "10": [
        "B L' R U' R' U L B'",
        "B' U' B' R L R' L' B'",
        "R' U' B' R L B' L' B'",
        "R' U' B U' B' U R",
        "R' B R U' R' B' R",
        "R' B' L B' L' B' R",
        "R B L U' L' B' R'",
        "L' U L U' L' U L",
        "L U' L U' L' U' L'",
        "R' L' B' L' B R L'"
    ],
    "11": [
        "B U B L B' L' U' B'",
        "B' R' L' R L B' U' B'",
        "R' B L' B' R B L B'",
        "R' U' R' U' R U' R",
        "R U R' U' R U R'",
        "L' B' R' U' R B L",
        "L U B' U' B U' L'",
        "R' L B R' B' R' L'",
        "L B' L' U' L B L'",
        "L B' R' B' R B' L'"
    ],
    "12": [
        "L R U B L' U R' B'",
        "L U B L R L R' B'",
        "B L' U' R U R' L B'",
        "R' U' B U B' U R",
        "L R' B' L B L R",
        "R' B L B L' B R",
        "R' B R U R' B' R",
        "R B L U L' B' R'",
        "L' U' L U L' U' L",
        "L U L U L' U L'"
    ],
    "13": [
        "B' U' B' L' B' L' U' L'",
        "R U' R' U R' L R L'",
        "L U L B L B U B",
        "L' B L B' U B' U' B",
        "R' U R U' R B' R' B",
        "R B' R' B U' B U B'",
        "R' U' R' B' R' B' U' B'",
        "L U' L' U L' B L B'",
        "R' U L' U L U' R",
        "R' U L' U' L U' R"
    ],
    "14": [
        "R' L R' B R B' R L'",
        "R L' U L U' L R' L'",
        "B R' B R B' L B' L'",
        "L' U' B' U' B' L' B' L'",
        "R' U R' U' R B' R B",
        "R' B' R B' L B L' B",
        "L B L' B R' B' R B'",
        "L U' L U L' B L' B'",
        "R U R' L R' L' R",
        "L' U' L U' R U R'"
    ],
    "15": [
        "R' U L B' U' L B' R L B'",
        "R B' L' R' B' R U R' L B'",
        "L B' U B L B' U B' L B'",
        "B R B' L' B' U R' B' L B'",
        "R B' L' B' U B R' B' L B'",
        "R' L R B' R' U' B' R L' B'",
        "B' R' B L B' U' B' R L' B'",
        "B' R' L B' U' B' R B L' B'",
        "L' B' U' B U' L R U R'",
        "R B U' L U' L' B' U R'"
    ],
    "16": [
        "B U' L' U L R U R' B'",
        "L R L' R' B R U R' B'",
        "R' B R L R L' U R' B'",
        "L' U' B U' R U L R' B'",
        "B L' B R U' B' L R' B'",
        "L' U R' L R L B L' B'",
        "R U R B U B' U' R",
        "L' B' U B L' R' L' R",
        "R' L R L' U R U R'",
        "R' B U B' U' R' U R'"
    ],
    "17": [
        "B' L B' L R U' R' L B'",
        "B R L' B U R' B' L B'",
        "R B L' U B R' B' L B'",
        "L B R' B' U' B R L' B'",
        "L U L U' L' U' B L' B'",
        "B' L B R' U' R B L' B'",
        "R U' R' U' L R' L' R",
        "L' U' L R B' R B R",
        "R U' R U B U' B' R",
        "L B L B' L R U' R'"
    ],
    "18": [
        "L' B U L' U' B U B L'",
        "B R' L B' U B' R B L'",
        "R U R' L' U' B L' B' L'",
        "L' B L' R' B' L' B' R B",
        "B R' B L R' L' U R' B",
        "B R U L' B R' U L B",
        "R' B L B' U B' R L' B",
        "B L' U R' L' R B L' B",
        "L' B' U R U B' L R' B'",
        "L' B' L' R' B L' U R"
    ],
    "19": [
        "R B U' B' U R L R L'",
        "L' U' L R U' R L R L'",
        "R' L R L' U' R' L R L'",
        "R B U' L' U' B R' L B",
        "L B' R' B U' B L' R B'",
        "B' R U' L R L' B' R B'",
        "B' L' U' R B' L U' R' B'",
        "B' L B' R' L R U' L B'",
        "R B' R L B R B L' B'",
        "L R' L R' U' R L R"
    ],
    "20": [
        "B R' L R U L' U' B'",
        "R' U L R L' B U' B'",
        "B U L' U' R' L R B'",
        "L' B U' R U L R' B'",
        "B U B L' B' U' L B'",
        "B R' B' L' B R L B'",
        "R' B' L' B R B L B'",
        "B U B L B' U' L' B'",
        "B R' B' L B R L' B'",
        "R' B' L B R B L' B'"
    ],
    "21": [
        "B' L B R B' L' R' B",
        "L B R B' L' B' R' B",
        "R B' U L' U' R' L B",
        "B' U' R U L R' L' B",
        "B R' L' R U L U' B'",
        "B L' U B L B' U' B'",
        "B L U B L' B' U' B'",
        "B U L U' R' L' R B'",
        "B L' R' B' L B R B'",
        "B L R' B' L' B R B'"
    ],
    "22": [
        "R' U B' U' R' U B R'",
        "R' B L' B L R' B R'",
        "R U B' L' B' L B' R'",
        "L B L B U' B U L",
        "R L B R' L U' B' L",
        "L U' B' U B' L B' L",
        "L' B L' B U' B U L'",
        "R' U' L U R' U' R' L'",
        "L' U' B' U B' L' B' L'",
        "R' L' R B L B U' B"
    ],
    "23": [
        "L' U' B R B R' B L",
        "L U' B U L U' B' L",
        "L B L' U L' U' B' L",
        "L B' R B' R' L B' L",
        "L' B U L' U' B' U L'",
        "R' L' U' L' U R U' L'",
        "B U' B R B L R' L'",
        "L' B L' R B R' B L'",
        "L' B U L U' L B' L'",
        "B L R L' B R' U B"
    ],
    "24": [
        "B' L U R B U' L' R'",
        "B' U' L R U B L' R'",
        "R U' B L' B L B R'",
        "L R U R' U' L U L",
        "R B' R B R L' U L",
        "L' B R B R' B U' L",
        "B' U' L' R' B U R L",
        "R U R' L B L B' L",
        "L' U L' B' U' B U L'",
        "L R U B L' R' U B'"
    ],
    "25": [
        "B U R L B' U' L' R'",
        "L' U' L R' B' R' B R'",
        "L U' B' U B L U' L",
        "B R' U' L' B' U R L",
        "B U R' L' U' B' R L",
        "B U R B' L' U' R' L",
        "L' U B' R B' R' B' L",
        "L' U' L' U R U' R' L'",
        "B U' R L B' U' R' L'",
        "L' R' U' B' R L U B"
    ],
    "26": [
        "B R B U B U B R' B'",
        "L B L' B R U' B' R' B'",
        "B' R U L' U L B' R' B'",
        "B' U L' R' B L U R",
        "R U' R U' L' U L R",
        "B L' B U B R' L R",
        "L' B' U B L R U R'",
        "L R' L' R U' R U' R'",
        "R' U' L' U L R' U' R'",
        "B L' U' B R L B R'"
    ],
    "27": [
        "R' B' U L' U' R B' L B'",
        "L' B' U' R U' R' B' L B'",
        "B U L' B L' B' U' L' B'",
        "L B' R' L B U' L R",
        "R' B' R' B' U B' U R'",
        "L' U L' R' L' R' U' R'",
        "L R' L' B' R' B U' R'",
        "R B' L' B' L U' B' R'",
        "R B U' L U' L' B' R'",
        "L U R U' R' L U L"
    ],
    "28": [
        "B R' L' R B' U' B L B'",
        "R' U R' B' L' R' B' L B'",
        "B U R U R' L U' L' B'",
        "R U R L' U' L U R",
        "B' L' U R' B L U R",
        "L' U' B L' B' R' L' R",
        "L R U' B R L' B' R",
        "R' L' U' L U R' U R'",
        "L' U' L' R' L' R' U R'",
        "L' B' R' U' R U' B L"
    ],
    "29": [
        "B U L' U' R' L' R L' B'",
        "R' B L B' R U' B L' B'",
        "B R' L R B' U' B L' B'",
        "L' U' L U' L R' L' R",
        "R U' B U' B R B R",
        "R B U L' B L B R'",
        "R B L U L' U B' R'",
        "L' U L R B U B' R'",
        "L R U R' U' L U' L",
        "R U R L R L U' L"
    ],
    "30": [
        "B' L' B U R B' R' L B",
        "B U' R L U' L' R' U B'",
        "L B' L U B L B U B'",
        "B U L U' L R' L R B'",
        "L U' B U' R' U L' R B'",
        "B' R U R B U B R B'",
        "R B' U B' L' U L R' B'",
        "B R L' B' L U B R' B'",
        "B' L B U B L U L B'",
        "R B' R L' B R B L B'"
    ],
    "31": [
        "R' U B' L R L' B' U' B'",
        "L U R' B R' L' U R' B'",
        "R' U' B' R B' R U' R' B'",
        "L' B' R B' U L U' R' B'",
        "R B' L' U' L B' U' R' B'",
        "B R B' U' L' B L R' B'",
        "L' B' U' R U B' L R' B'",
        "R' B' L' R' B R' B L B'",
        "L' U' B' R U' R' B' L B'",
        "R' U B' R' L' R' B' L B'"
    ],
    "32": [
        "B L' B' R U R' B L B'",
        "B R L' R' B U B' L B'",
        "R' L' R U B' U B' L B'",
        "B' R' B L U' B R L' B'",
        "B' R' L B U' R B L' B'",
        "B L' B R' L B U' R",
        "R U B' R B R' U R'",
        "L' U L' B L B' U L",
        "B L' B R U R' B L",
        "R' L' R' U' R L' R L'"
    ],
    "33": [
        "L' R B' U' B R' B L B'",
        "B' R' L' R L' B' U' L' B'",
        "B R' B' L' B L' R L' B'",
        "B' R' U' B' R' L R' L' B'",
        "R' L' R L' B' U' B' L' B'",
        "L R' L R' U R L R",
        "L R B' R L B L R",
        "L R B R L B' L R",
        "L R L U L' R L' R",
        "B' R' L B' U' L' B' R"
    ],
    "34": [
        "R B' R' L R' L' B R",
        "R L U' L' B R B' R",
        "R' B R' B' L U L' R'",
        "L' R' L R' B' U' B R'",
        "R' B' L R L' R B R'",
        "L R' L' R U' L' U L",
        "R' B' R' B R' L' U' L",
        "R B' U B R L' R L",
        "L B L R B R' B L",
        "B' R B' R' L B' U L'"
    ],
    "35": [
        "L U' B' U B R' L' R",
        "R B L' B L R B R",
        "L B L B' L R U R'",
        "R' L R L' U R U' R'",
        "L' B U' B' L' R L' R'",
        "R' B' R' L' B' L B' R'",
        "L B' L B R' U' R L",
        "R L R' L B U B' L",
        "L B R' L' R L' B' L",
        "R' L R B' U' B U L'"
    ]
};